### ISSUE TITLE
Separate build from deploy

### ISSUE THREAD

**Issue by altaurog** [pullpreview/action#14]
This is an interesting project, I think it could be quite useful for us.  In our test, we had to pick a larger instance than we would have used for the app because the docker build requires more resources.
Is there a way to separate the build out so that can be done on a separate system and then deployed to lightsail?

**Comment by crohr** [comment]
@altaurog sure, you could build your docker image as a first GitHub action step, push to GitHub container registry, and then reference that image from your compose file. Would that work for you?

**Comment by altaurog** [comment]
sure, thanks!  That makes sense.  We will give that a whirl
