### ISSUE TITLE
DNS questions

### ISSUE THREAD

**Issue by altaurog** [pullpreview/action#16]
Okay, now we have some dns questions.  I see support for custom dns is a recent commit; what exactly does this mean/entail?  If we want to run this on our own domain, is that supported?  What configuration do we need on our end?

A related problem is we need the url as a parameter for the build.  This works when we build on the lightsail instance, but as proposed in #14 we would like to run the build separately.  So we either need a way to determine the pullpreview url in advance so we can use it in the build or pass pullpreview an externally assigned dns name (is this just a matter of simplifying the dns_name function in instance.rb?)

**Comment by altaurog** [comment]
We are able to set our own dns in the build and setup a CNAME record pointing to the hostname we get back from pullpreview, but it doesn’t seem to work with a different hostname in the request.  It would help to understand how dns works for these lightsail instances.  Is that a secret?

**Comment by altaurog** [comment]
There might be some other issue, but A record to the IP address also doesn’t seem to work.

**Comment by altaurog** [comment]
Okay, so A record is working. I guess it would be nice to disable the pullpreview.com DNS

**Comment by altaurog** [comment]
Also, if we use a different DNS address, the deployment link posted in the PR won’t work, which makes this much less useful

**Comment by crohr** [comment]
@altaurog sorry for the delay, but you can use your own custom domain by setting `dns: preview.yourdomain.com` in the workflow. This assumes that you added a NS record from preview.yourdomain.com to `xip.pullpreview.com`.  Then everything should just work.

**Comment by crohr** [comment]
Regarding the availability of the url at build time, the best way to do this is fix your app so that it can take the correct URL at runtime from the env variable. If you are building e.g. static sites, then add an entrypoint to your dockerfile that search and replace the placeholder URL by the pullpreview URL.
