### ISSUE TITLE
pullpreview/action@master unable to ssh into lightsail instance

### ISSUE THREAD

**Issue by paritoshcm** [pullpreview/action#23]
Hello, we have been using pullpreview for our PR deployments, and it has been going pretty well! Really helpful service!

Unfortunately, today all our deployment actions are failing, with the `pullpreview/action@master` step being unable to ssh into the created lightsail instance.
```log
I, [2021-12-01T07:37:58.686945 #1]  INFO -- : Waiting for instance to be running
I, [2021-12-01T07:38:04.443650 #1]  INFO -- : Waiting for instance to be running
I, [2021-12-01T07:38:07.408233 #1]  INFO -- : Instance is running public_ip=a.b.c.d public_dns=pr-128-name-a-b-c-d.my.pullpreview.com
I, [2021-12-01T07:38:09.410493 #1]  INFO -- : Synchronizing instance name=gh-123456789-pr-128
I, [2021-12-01T07:38:10.844121 #1]  INFO -- : Waiting for ssh
ssh: connect to host a.b.c.d port 22: Connection refused
I, [2021-12-01T07:38:16.939723 #1]  INFO -- : Waiting for ssh
ssh: connect to host a.b.c.d port 22: Connection refused
I, [2021-12-01T07:38:22.021535 #1]  INFO -- : Waiting for ssh
ls-user@a.b.c.d: Permission denied (publickey).
I, [2021-12-01T07:38:27.661637 #1]  INFO -- : Waiting for ssh
ls-user@a.b.c.d: Permission denied (publickey).
I, [2021-12-01T07:38:33.491101 #1]  INFO -- : Waiting for ssh
ls-user@a.b.c.d: Permission denied (publickey).
...
I, [2021-12-01T07:40:54.428944 #1]  INFO -- : Waiting for ssh
ls-user@a.b.c.d: Permission denied (publickey).
E, [2021-12-01T07:40:55.063092 #1] ERROR -- : Instance ssh access KO
Error: Can't connect to instance over SSH. Aborting.
```
I have obfuscated hosts, names, and ids, but I hope the error is clear.

Nothing has changed on our end, both in the repository or in the AWS settings. The action was working fine, it's just today it's unable to ssh to the instance.

If we do it manually or through the lightsail UI, we are able to ssh into the instance without any issues.

So, we're not sure if it's something in the action itself that's preventing the ssh.

Please let us know if you're aware of the reason behind this issue, and how to fix it. The deployments not working really affects our workflow.

**Comment by crohr** [comment]
Hello, I can confirm the issue. Nothing has changed in the action and GitHub goes straight to AWS to connect, so there must have been some change in Lightsail itself. I'm investigating.

**Comment by matthieubc** [comment]
We are getting the same issue. Thanks!

**Comment by crohr** [comment]
`v5` and `master` are using a new base docker image to fix the issue with SSH connection. Please let me know if the issue is fixed for you, and please remember to buy a license to support the ongoing maintenance for this project :). Thanks!

**Comment by paritoshcm** [comment]
Thanks you so much for the quick fix, @crohr! The issue is fixed, and deployments are working!

I'll definitely push for purchasing a license!
