### ISSUE TITLE
yum update

### ISSUE THREAD

**Issue by altaurog** [pullpreview/action#31]
It seems that we occasionally need to run `yum update` on the pullpreview lightsail instances to get them to work.  (I have no idea why this is).  Could we have an option to do yum update automatically before `docker-compose up`?

**Comment by crohr** [comment]
@altaurog can you try with `pullpreview/action@master` and see if that fixes your issue?

**Comment by altaurog** [comment]
Thank you @crohr, we are indeed using `pullpreview/action@master`, I’ll keep an eye on it.
