### ISSUE TITLE
Permission denied for SSH

### ISSUE THREAD

**Issue by EmberRandall** [pullpreview/action#51]
When my preview environment spins up, it ends with output like

```
You can access your application at the following URL: <url>

To connect to the instance (authorized GitHub users: ... EmberRandall):
  ssh ec2-user@<ip>

Then to view the logs:
  docker-compose logs --tail 1000 -f
```

According to that output, I should be able to ssh into the instance, because my Github user is one of the authorized ones. However, I'm getting `Permission denied (publickey,gssapi-keyex,gssapi-with-mic)`, and I'm not sure how to debug that. Is there something else needed for me to ssh?

**Comment by crohr** [comment]
@EmberRandall Which distribution are you on? Could you check your openssh version with `ssh -V` ?

**Comment by crohr** [comment]
@EmberRandall this should be fixed with the latest `v5` commit. Just ensure you re-create a new pullpreview instance to benefit from the upgraded OS on the instance.
