### ISSUE TITLE
How can I login to a private registry

### ISSUE THREAD

**Issue by reaper** [pullpreview/action#59]
Ahoy !
I want to login to a private docker registry (for ex ECR) but I can't execute the docker login command before the docker compose file is processed.

My docker compose file contains private docker images and I cannot fetch them.
We don't want to use GHCR.

How should I proceed ? Please advice.
Thanks

**Comment by crohr** [comment]
Sure, have you seen this wiki page? https://github.com/pullpreview/action/wiki/Private-docker-registries

**Comment by reaper** [comment]
You're awesome, thanks !

Got it working with the following:

 ```
 with:
   registries: docker://AWS:${{ secrets.AWS_ECR_TOKEN }}@XXXXXXXX.dkr.ecr.XXXX.amazonaws.com
```

the secret `secrets.AWS_ECR_TOKEN` is the password generated with the command `aws ecr get-login-password`
