### ISSUE TITLE
EC2 Support

### ISSUE THREAD

**Issue by richard5mith** [pullpreview/action#71]
Any plans to support EC2 as well as Lightsail?

The problem is that Lightsail doesn't support private DNS or IAM roles, both of which are necessary for our application to be able to speak to other AWS services and communicate with other applications in our dev environment.

**Comment by crohr** [comment]
Hello, I was just thinking about it yesterday, no concrete plan for now though. 

Can you give a bit more details on your specific requirements though?

I suppose the instance would need to be placed in a specific VPC to get access to the private DNS, and for IAM roles, could you give an example that the app should have?

Thanks!

**Comment by richard5mith** [comment]
Our application normally runs in Fargate or on EC2, both via ECS. In both those cases you can assign an IAM role to the Fargate instance or the EC2 so that we don't need to manage any AWS credentials in our application. We use Python with boto3 and it automatically gets it's IAM role from the host, allowing us to do what we need to do with S3 etc.

The private IP is because we have multiple services running across different containers. So for the services to talk to each other, they do so through a private Application Load Balancer, which we have private DNS entries for in Route 53. Again, EC2 and Fargate because they're in our VPC and chosen subnets get automatic access to that internal DNS without the application needing to know.

So to run it on Lightsail we'd need to have a set of credentials and an IAM user with a role assigned, and put them somewhere on the host that boto3 could find them. That's just less secure, as it would probably mean putting them into Github secrets and writing them to the host as part of the startup. For the private DNS - I'm not even sure. Somehow put something in the /etc/hosts file maybe. 

For EC2, it would just require the additional configuration values of which VPC and Subnets the instance should be placed in, the security group id it should use, and the optional IAM role that should be assigned to the instance. There'd still be an instance type, but the image id could be fixed. It's additional work for the AWS account owner, but I don't think it would be that much more complicated from pull-preview point of view, it's just a different API call to create the instance.

**Comment by crohr** [comment]
Thanks for the detailed answer. I agree it would be feasible (main point being the need for short-lived SSH credentials to connect to the instances from the GitHub Action, but EC2 supports [sending short-lived SSH keys](https://docs.aws.amazon.com/ec2-instance-connect/latest/APIReference/API_SendSSHPublicKey.html) so that should work).

Assuming I develop the feature for EC2 support, would you be able to beta-test it?

**Comment by richard5mith** [comment]
Absolutely. And we'll pay for a license too, because we can definitely see the benefit.

**Comment by crohr** [comment]
I'm sorry but I don't have the time currently to enable support for EC2. I'm going to close this issue and maybe revisit when I'll have more time (my other project [RunsOn](https://runs-on.com) is really taking off).
