### ISSUE TITLE
Port baked into PULLPREVIEW_URL causing issues

### ISSUE THREAD

**Issue by geoffatsource** [pullpreview/action#74]
I'd like to be able to set up Caddy to serve from two different ports but since the port is baked into the env variable it's causing issues. Is there a way around this?

**Comment by geoffatsource** [comment]
I will try changing my Caddyfile to use path matchers instead

```
{$PULLPREVIEW_URL} {
  handle_path not /v1/graphql* {
    reverse_proxy http://client:3000
  }
  handle_path /v1/graphql* {
    reverse_proxy http://api:8080
  }
}
```

**Comment by geoffatsource** [comment]
I know this is a Caddy thing but I'm not able to get this to work with the path matchers under one port. I think we need a way to get the `PULLPREVIEW_URL` without the port

**Comment by crohr** [comment]
Hello, if you only want the host, have you tried using `PULLPREVIEW_PUBLIC_DNS`? And building URLs around it if needed?

**Comment by geoffatsource** [comment]
I may try that in the future, but I got it working better using a single port and path matchers.... a lot cleaner. Thanks!
