### ISSUE TITLE
Some Pullpreview workflow options can break things

### ISSUE THREAD

**Issue by geoffatsource** [pullpreview/action#75]
Just a couple of things I ran into when integrating this great tool:

- Note that removing port 80 from `ports:` will break SSL cert challenge response
- Enabling `cidrs:` will also break SSL challenge response. It would be nice if there was a way to enable that _only after_ successful cert installation

**Comment by crohr** [comment]
Ah yes correct. Enabling firewall will mess with let's encrypt http challenge, same if disabling port 80. Not sure I have any idea to remedy this yet (except for enabling dns challenge on your side instead).

**Comment by crohr** [comment]
Thanks for all the feedback! Hopefully you got it working still?

**Comment by geoffatsource** [comment]
Yes I did get it working. Thanks! I will definitely be investing in a license.
