### ISSUE TITLE
How do we use PULLPREVIEW_FIRST_RUN in our docker compose?

### ISSUE THREAD

**Issue by geoffatsource** [pullpreview/action#76]
I was reading about seed data, and I see you recently added this new environment variable, but I am not clear how to use it. Can you elaborate and/or update the docs with an example usage?

**Comment by crohr** [comment]
Have you seen the wiki page about it? https://github.com/pullpreview/action/wiki/Seed-Data#seeding-using-a-dump-from-a-production-database
